"use strict";(self.webpackChunk_agentscope_ai_design=self.webpackChunk_agentscope_ai_design||[]).push([[5682],{70039:function(v,u,n){n.r(u),n.d(u,{default:function(){return e}});var O=n(5574),g=n.n(O),a=n(57027),_=n(76561),x=n(67294),t=n(85893);function e(){var p=(0,x.useState)(!1),C=g()(p,2),f=C[0],i=C[1];return(0,t.jsxs)(t.Fragment,{children:[(0,t.jsx)(a.Z,{onClick:function(){return i(!0)},children:"Open Modal"}),(0,t.jsx)(_.Z,{title:"Basic Title",centered:!0,open:f,onOk:function(){return i(!1)},onCancel:function(){return i(!1)},children:(0,t.jsx)("div",{style:{display:"flex",alignItems:"center",justifyContent:"center",borderRadius:6,color:"var(--sps-color-text-tertiary)",border:"1px solid var(--sps-color-border-secondary)",height:312,fontSize:24,background:`repeating-linear-gradient(
              135deg,
              var(--sps-color-border-secondary) 0,
              var(--sps-color-border-secondary) 1px,
              var(--sps-color-bg-base) 1px,
              var(--sps-color-bg-base) 15px
              )`},children:"Content"})})]})}},30254:function(v,u,n){n.r(u),n.d(u,{default:function(){return E}});var O=n(5574),g=n.n(O),a=n(57027),_=n(76561),x=n(86250),t=n(67294),e=n(85893);function p(s){var o=s.border,c=o===void 0?!0:o;return(0,e.jsx)("div",{style:{display:"flex",alignItems:"center",justifyContent:"center",borderRadius:6,color:"var(--sps-color-text-tertiary)",border:c?"1px solid var(--sps-color-border-secondary)":"none",height:312,fontSize:24,background:`repeating-linear-gradient(
          135deg,
          var(--sps-color-border-secondary) 0,
          var(--sps-color-border-secondary) 1px,
          var(--sps-color-bg-base) 1px,
          var(--sps-color-bg-base) 15px
          )`},children:"Content"})}function C(){var s=(0,t.useState)(!1),o=g()(s,2),c=o[0],r=o[1];return(0,e.jsxs)(e.Fragment,{children:[(0,e.jsx)(a.Z,{onClick:function(){return r(!0)},children:"No divider"}),(0,e.jsx)(_.Z,{centered:!0,showDivider:!1,title:"Basic Modal",open:c,onOk:function(){return r(!0)},onCancel:function(){return r(!1)},styles:{body:{paddingTop:0,paddingBottom:0}},children:(0,e.jsx)(p,{})})]})}function f(){var s=(0,t.useState)(!1),o=g()(s,2),c=o[0],r=o[1];return(0,e.jsxs)(e.Fragment,{children:[(0,e.jsx)(a.Z,{onClick:function(){return r(!0)},children:"No Padding"}),(0,e.jsx)(_.Z,{centered:!0,styles:{body:{padding:0}},title:"Basic Modal",open:c,onOk:function(){return r(!0)},onCancel:function(){return r(!1)},children:(0,e.jsx)(p,{border:!1})})]})}function i(){var s=(0,t.useState)(!1),o=g()(s,2),c=o[0],r=o[1];return(0,e.jsxs)(e.Fragment,{children:[(0,e.jsx)(a.Z,{onClick:function(){return r(!0)},children:"Custom footer"}),(0,e.jsx)(_.Z,{centered:!0,title:"Basic Modal",open:c,onOk:function(){return r(!0)},onCancel:function(){return r(!1)},footer:(0,e.jsx)(a.Z,{children:"Custom footer"}),children:(0,e.jsx)(p,{})})]})}function l(){var s=(0,t.useState)(!1),o=g()(s,2),c=o[0],r=o[1];return(0,e.jsxs)(e.Fragment,{children:[(0,e.jsx)(a.Z,{onClick:function(){return r(!0)},children:"Footer With Info"}),(0,e.jsx)(_.Z,{centered:!0,title:"Basic Modal",open:c,onOk:function(){return r(!0)},onCancel:function(){return r(!1)},info:(0,e.jsx)("div",{children:"info here"}),children:(0,e.jsx)(p,{})})]})}function E(){return(0,e.jsxs)(x.Z,{vertical:!0,gap:24,align:"center",children:[(0,e.jsx)(C,{}),(0,e.jsx)(f,{}),(0,e.jsx)(i,{}),(0,e.jsx)(l,{})]})}},52057:function(v,u,n){n.r(u),n.d(u,{default:function(){return C}});var O=n(5574),g=n.n(O),a=n(57027),_=n(76561),x=n(86250),t=n(67294),e=n(85893);function p(f){var i=f.border,l=i===void 0?!0:i;return(0,e.jsx)("div",{style:{display:"flex",alignItems:"center",justifyContent:"center",borderRadius:6,color:"var(--sps-color-text-tertiary)",border:l?"1px solid var(--sps-color-border-secondary)":"none",height:312,fontSize:24,background:`repeating-linear-gradient(
          135deg,
          var(--sps-color-border-secondary) 0,
          var(--sps-color-border-secondary) 1px,
          var(--sps-color-bg-base) 1px,
          var(--sps-color-bg-base) 15px
          )`},children:f.children})}function C(){var f=(0,t.useState)(0),i=g()(f,2),l=i[0],E=i[1];return(0,e.jsxs)(x.Z,{gap:16,children:[(0,e.jsx)(a.Z,{onClick:function(){return E(_.Z.SMALL_WIDTH)},children:"Small (640px)"}),(0,e.jsx)(a.Z,{onClick:function(){return E(_.Z.MEDIUM_WIDTH)},children:"Middle (800px)"}),(0,e.jsx)(a.Z,{onClick:function(){return E(_.Z.LARGE_WIDTH)},children:"Large (960px)"}),(0,e.jsx)(_.Z,{centered:!0,title:"Basic Modal",open:!!l,width:l,onOk:function(){return E(0)},onCancel:function(){return E(0)},children:(0,e.jsxs)(p,{children:["Content here for ",l,"px"]})})]})}}}]);
